draw_config:
  # Key dimensions
  key_w: 60     # Width of each key
  key_h: 56     # Height of each key

  # Outline settings
  outline:
    stroke_width: 2  # Width of the outline
    stroke_color: "#000000"  # Color of the outline (black)
    fill_color: "transparent"  # Fill color (transparent for just an outline)

  # Padding settings
  outer_pad_w: 10  # Padding around the keyboard outline
  outer_pad_h: 10  # Padding between layers, if applicable
  inner_pad_w: 2   # Padding between keys horizontally
  inner_pad_h: 2   # Padding between keys vertically

  # Key curvature
  key_rx: 6  # Rounded corners of the keys
  key_ry: 6

  # Additional settings
  n_columns: 1  # Number of columns for layers
  dark_mode: false  # Enable dark mode if needed
  svg_style: |
    .keyboard-outline {
      stroke: {{ outline.stroke_color }};
      stroke-width: {{ outline.stroke_width }};
      fill: {{ outline.fill_color }};
    }

parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&ext_power EP_TOG': "🔌"
    "&caps_word": $$mdi:alpha-w-box$$
    '&bootloader': "💾"
    '&sys_reset': "🔄"
    '&reset_td': "🔄"
    '&dot_space_shift': ".⎵⇧"

    "&ltsk MEDIA LSHIFT":
      tap: SK(⇧)
      hold: MEDIA
    "&ltr NUM 0":
      tap: $$mdi:repeat-variant$$
      hold: $$mdi:numeric$$

    "&ltsk NUM BSPC":
      tap: $$mdi:backspace-outline$$
      hold: $$mdi:numeric$$

    "&lt MOUSE ESC":
      tap: $$mdi:keyboard-esc$$
      hold: $$mdi:mouse$$

    "&lt NAV SPACE":
      tap: $$mdi:keyboard-space$$
      hold: $$mdi:navigation-variant-outline$$

    "&lt FUN RET":
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:function-variant$$

    # Bluetooth
    "&bt BT_SEL 0":
      tap: $$mdi:bluetooth-connect$$
      hold: 0
    "&bt BT_SEL 1":
      tap: $$mdi:bluetooth-connect$$
      hold: 1
    "&bt BT_SEL 2":
      tap: $$mdi:bluetooth-connect$$
      hold: 2
    "&bt BT_SEL 3":
      tap: $$mdi:bluetooth-connect$$
      hold: 3
    "&bt BT_SEL 4":
      tap: $$mdi:bluetooth-connect$$
      hold: 4
    '&bt BT_NXT':
      tap: $$mdi:bluetooth-connect$$
      hold: $$mdi:chevron-right$$
    '&bt BT_PRV':
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:chevron-left$$
    '&bt BT_CLR':
      tap: $$mdi:bluetooth-connect$$
      hold: $$mdi:close-box-outline$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$

    "&thread_arrow":
      tap: ->
      shifted: =>
    "&and":
      tap: and

  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans
  mark_alternate_layer_activators: false
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RGUI: $$mdi:apple-keyboard-command$$

    # "Meh" key
    LS(LC(LALT)): $$mdi:star-three-points$$
    LC(INS): "📄"
    LS(INS): "📋"
    LS(DEL): "✂️"
    LG(Q): "⌘Q"
    LC(W): "⌃W"
    LC(T): "⌃T"
    LC(TAB): "⌃⇥"
    LS(LC(TAB)): "⇧⌃⇥"
    RC(BSPC): ^BSPC

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    _SPC_: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    K_MUTE: $$mdi:volume-off$$
    K_VOL_UP: $$mdi:volume-high$$
    K_VOL_DN: $$mdi:volume-low$$

    # Media
    K_NEXT: $$mdi:skip-next$$
    K_PREV: $$mdi:skip-previous$$
    K_PP: $$mdi:play-pause$$
    K_STOP2: $$mdi:stop-circle-outline$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$
    K_REDO: $$mdi:redo$$
    K_PASTE: $$mdi:content-paste$$
    K_COPY: $$mdi:content-copy$$
    K_CUT: $$mdi:content-cut$$
    K_UNDO: $$mdi:undo-variant$$

  zmk_combos: {}
