name: ZMK Workflow

on:
  push: 
    branches: 
      - main  # Specify your main branch
  pull_request: 
    branches: 
      - main  # Specify your main branch
  workflow_dispatch:  # can be triggered manually

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  draw:
    needs: build  
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write 
    with:
      keymap_patterns: "config/*.keymap"        # path to the keymaps to parse
      config_path: "keymap_drawer.config.yaml"  # config file, ignored if not exists
      output_folder: "keymap-drawer"            # path to save produced SVG and keymap YAML files
      parse_args: ""  # map of extra args to pass to `keymap parse`
      draw_args: ""   # map of extra args to pass to `keymap draw`
